package br.app.camarada.backend.enums;

public enum TextosBundle {
    VERIFICADO,
    BIO,
    ROTULO_PERFIL_IDADE,QUERO_SER_CONHECIDO_POR,
    TITULO_ERRO_PAGAMENTO_PENDENTE_PIX,
    TITULO_ERRO_PAGAMENTO_PENDENTE_E_CANCELADO_PIX, DESCRICAO_ERRO_PAGAMENTO_PENDENTE_E_CANCELADO_PIX, DESCRICAO_ERRO_PAGAMENTO_PENDENTE_PIX

}
